### ISSUE TITLE
BL7 upgrade: better fit text and button on landing page card back

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1555]
I think this might be a Spotlight fix but will file in Exhibits since the devs know better than me the status of things with regard to what's currently handled in Spotlight versus Exhibits.

The site landing page card backs don't always contain their contents very well at less than the `xl` viewport width:

<img width="487" alt="Screen Shot 2020-01-24 at 5 22 27 PM" src="https://user-images.githubusercontent.com/101482/73112943-5183d200-3ece-11ea-9c91-886b68926864.png">

A couple of SCSS updates that should improve this:

```css

.card-back {
  padding: 0 1rem; // currently: 0 30px
}

.card-back .visit-exhibit {
  bottom: 1rem; // currently: 30px
}
```

Result:

<img width="487" alt="Screen Shot 2020-01-24 at 5 23 52 PM" src="https://user-images.githubusercontent.com/101482/73112964-6e200a00-3ece-11ea-978e-d626d9c4ebe1.png">
