### ISSUE TITLE
Improve text of confirmation email

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#531]
The current email sent when a user is added as a curator or admin to an exhibit is not customized enough to avoid looking generic and spam-like. 

The text used for invitation instructions is better, but for confirmation instructions we're just using the default generic text, I think:

```
   mailer:
      confirmation_instructions:
        subject: "Confirmation instructions"
      invitation_instructions:
        subject: 'SUL exhibit invitation instructions'
```

This produces an email like:

> From: exhibits-team@lists.stanford.edu <exhibits-team@lists.stanford.edu>
Sent: Monday, August 14, 2017 3:50 PM
To: Some User
Subject: Confirmation instructions
 
> Welcome some-user@stanford.edu!
You can confirm your account email through the link below:
Confirm my account

We should update the locale text to produce a more customized and non-spam appearing email.
